### ISSUE TITLE
`create-local-dynamodb-table.ts` 파일 rename 필요

### ISSUE THREAD

**Issue by hqafqd** [aluc-io/anonymouslack#29]
create-local-dynamodb-table.ts 파일 이름에 `local` 이 붙어서 local dynamo db 를 셋업할 때만 커멘드가 필요한 것으로 보여 헷갈립니다.
`create-local-dynamodb-table.ts` -> `create-dynamodb-table.ts` 파일 리네임 검토 부탁드립니다

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
resolved by #36
